/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type CoreCtaFragment = { __typename: 'CoreCtaRecord', id: string, title: string | null, seoTitle: string | null, path: string | null, style: string | null, colorType: string | null, size: string | null, target: string | null, action: string | null, actionDetail: string | null, icon: string | null, link: { __typename: 'PageRecord', entry: { __typename: 'PageConfigRecord', handle: string | null } } | { __typename: 'PostRecord', entry: { __typename: 'PostConfigRecord', handle: string | null } } | { __typename: 'SupercarRecord', entry: { __typename: 'SupercarConfigRecord', handle: string | null } } | { __typename: 'TrackRecord', entry: { __typename: 'TrackConfigRecord', handle: string | null } } | null };
