/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type GetSiteQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetSiteQuery = { __typename: 'Query', _site: { __typename: 'Site', faviconMetaTags: Array<{ __typename: 'Tag', tag: string, attributes: Record<string, string> | null, content: string | null }>, globalSeo: { __typename: 'GlobalSeoField', siteName: string | null, titleSuffix: string | null, twitterAccount: string | null, facebookPageUrl: string | null, fallbackSeo: { __typename: 'SeoField', title: string | null, description: string | null, noIndex: boolean | null, twitterCard: string | null, image: { __typename: 'FileField', id: string, format: string, url: string, width: number | null, height: number | null, alt: string | null, title: string | null, focalPoint: { __typename: 'focalPoint', x: number, y: number } | null, responsiveImage: { __typename: 'ResponsiveImage', src: string, srcSet: string, sizes: string, height: number, aspectRatio: number, width: number, alt: string | null, title: string | null, base64: string | null, bgColor: string | null } | null } | null } | null } | null } };
