/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type SectionSupercarBrandGridFragment = { __typename: 'SectionSupercarBrandGridRecord', id: string, title: string | null, description: string | null, config: { __typename: 'SectionConfigRecord', id: string, customId: string | null, enabled: boolean, mode: string | null, highlightColor: string | null, contrastColor: string | null, addBottomBorder: boolean, addFlagPattern: boolean } | null, logos: Array<{ __typename: 'FileField', id: string, format: string, url: string, width: number | null, height: number | null, alt: string | null, title: string | null, focalPoint: { __typename: 'focalPoint', x: number, y: number } | null, responsiveImage: { __typename: 'ResponsiveImage', src: string, srcSet: string, sizes: string, height: number, aspectRatio: number, width: number, alt: string | null, title: string | null, base64: string | null, bgColor: string | null } | null }> };
