#!/bin/bash

set -Eeuxo pipefail

export DOCKER_BUILDKIT=1
export COMPOSE_BAKE=1
export COMPOSE_DOCKER_CLI_BUILD=1

docker compose build db typesense main \
  && docker compose up -d main \
  && docker compose exec main ./docker-entrypoint.sh /usr/bin/fish
