/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type CoreGradientFragment = { __typename: 'CoreGradientRecord', enabled: boolean, direction: string | null, customCssGradient: string | null, startColor: { __typename: 'ColorField', cssRgb: string } | null, endColor: { __typename: 'ColorField', cssRgb: string } | null };
