/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type CoreFormFieldFragment = { __typename: 'CoreFormFieldRecord', id: string, fieldType: string, fieldName: string, fieldRequired: boolean, fieldLabel: string, fieldPlaceholder: string | null, fieldSize: string, fieldError: string | null, fieldOptions: Array<{ __typename: 'CoreFormFieldOptionRecord', id: string, optionLabel: string, optionValue: string }> };
