/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type CoreIconFragment = { __typename: 'CoreIconRecord', id: string, icon: string | null };
