/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type AddonModelDataFragment = { __typename: 'AddonModelRecord', id: string, title: string | null, description: string | null, rocketRezId: string, rocketRezType: string };
