/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type FormModelFragment = { __typename: 'FormModelRecord', id: string, formProvider: string, formSubmitButton: string | null, successTitle: string | null, successDescription: string | null, errorTitle: string | null, errorDescription: string | null, successButton: { __typename: 'CoreCtaRecord', id: string, title: string | null, seoTitle: string | null, path: string | null, style: string | null, colorType: string | null, size: string | null, target: string | null, action: string | null, actionDetail: string | null, icon: string | null, link: { __typename: 'PageRecord', entry: { __typename: 'PageConfigRecord', handle: string | null } } | { __typename: 'PostRecord', entry: { __typename: 'PostConfigRecord', handle: string | null } } | { __typename: 'SupercarRecord', entry: { __typename: 'SupercarConfigRecord', handle: string | null } } | { __typename: 'TrackRecord', entry: { __typename: 'TrackConfigRecord', handle: string | null } } | null } | null, formFields: Array<{ __typename: 'CoreFormFieldRecord', id: string, fieldType: string, fieldName: string, fieldRequired: boolean, fieldLabel: string, fieldPlaceholder: string | null, fieldSize: string, fieldError: string | null, fieldOptions: Array<{ __typename: 'CoreFormFieldOptionRecord', id: string, optionLabel: string, optionValue: string }> }> };
