/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type InsuranceFragment = { __typename: 'InsuranceRecord', id: string, titleInternal: string | null, _createdAt: string, _updatedAt: string, model: { __typename: 'InsuranceModelRecord', id: string, title: string | null, rocketRezId: string, rocketRezType: string, description: string | null, coverage: string | null, price: { __typename: 'CorePriceRecord', id: string, compareAtPrice: number | null, price: number | null } | null, badge: { __typename: 'CoreBadgeRecord', id: string, label: string | null, backgroundColor: { __typename: 'ColorField', hex: string } | null, color: { __typename: 'ColorField', hex: string } | null } | null, thumbnail: { __typename: 'CoreImageRecord', id: string, image: { __typename: 'FileField', id: string, format: string, url: string, width: number | null, height: number | null, alt: string | null, title: string | null, focalPoint: { __typename: 'focalPoint', x: number, y: number } | null, responsiveImage: { __typename: 'ResponsiveImage', src: string, srcSet: string, sizes: string, height: number, aspectRatio: number, width: number, alt: string | null, title: string | null, base64: string | null, bgColor: string | null } | null } | null, desktopImage: { __typename: 'FileField', id: string, format: string, url: string, width: number | null, height: number | null, alt: string | null, title: string | null, focalPoint: { __typename: 'focalPoint', x: number, y: number } | null, responsiveImage: { __typename: 'ResponsiveImage', src: string, srcSet: string, sizes: string, height: number, aspectRatio: number, width: number, alt: string | null, title: string | null, base64: string | null, bgColor: string | null } | null } | null } | null } | null };
