/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type PolicyFragment = { __typename: 'PolicyRecord', id: string, model: { __typename: 'PolicyModelRecord', id: string, title: string | null, body: string | null } | null };
