/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type PostConfigFragment = { __typename: 'PostConfigRecord', id: string, handle: string | null, seo: { __typename: 'SeoField', title: string | null, description: string | null, noIndex: boolean | null, twitterCard: string | null, image: { __typename: 'FileField', id: string, format: string, url: string, width: number | null, height: number | null, alt: string | null, title: string | null, focalPoint: { __typename: 'focalPoint', x: number, y: number } | null, responsiveImage: { __typename: 'ResponsiveImage', src: string, srcSet: string, sizes: string, height: number, aspectRatio: number, width: number, alt: string | null, title: string | null, base64: string | null, bgColor: string | null } | null } | null } | null };
