/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type SectionSupercarGridConfigFragment = { __typename: 'SectionSupercarGridConfigRecord', id: string, layout: string | null, showFilters: boolean, addCardLinks: boolean, cardType: string | null, cardBackgroundColor: string | null, headerBorder: boolean, headerHorizontalAlignment: string | null };
