/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type SectionConfigFragment = { __typename: 'SectionConfigRecord', id: string, customId: string | null, enabled: boolean, mode: string | null, highlightColor: string | null, contrastColor: string | null, addBottomBorder: boolean, addFlagPattern: boolean, enableCampaignStickyBar: boolean, campaignStickyBarHeading: string | null, campaignStickyBarTimerEnd: string | null, campaignStickyBarCtaTitle: string | null, campaignStickyBarCtaLink: string | null, campaignStickyBarBackgroundColor: string | null, campaignStickyBarTextColor: string | null, campaignStickyBarTimerColor: string | null, campaignStickyBarButtonBackgroundColor: string | null, campaignStickyBarButtonTextColor: string | null };
