/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type SitemapSupercarsQueryVariables = Types.Exact<{
  first: Types.Scalars['IntType']['input'];
  skip: Types.Scalars['IntType']['input'];
}>;


export type SitemapSupercarsQuery = { __typename: 'Query', allSupercars: Array<{ __typename: 'SupercarRecord', _updatedAt: string, config: { __typename: 'SupercarConfigRecord', handle: string | null, seo: { __typename: 'SeoField', noIndex: boolean | null } | null } }> };
