/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type SitemapTracksQueryVariables = Types.Exact<{
  first: Types.Scalars['IntType']['input'];
  skip: Types.Scalars['IntType']['input'];
}>;


export type SitemapTracksQuery = { __typename: 'Query', allTracks: Array<{ __typename: 'TrackRecord', _updatedAt: string, config: { __typename: 'TrackConfigRecord', handle: string | null, seo: { __typename: 'SeoField', noIndex: boolean | null } | null } }> };
