/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type SitemapPagesQueryVariables = Types.Exact<{
  first: Types.Scalars['IntType']['input'];
  skip: Types.Scalars['IntType']['input'];
}>;


export type SitemapPagesQuery = { __typename: 'Query', allPages: Array<{ __typename: 'PageRecord', _updatedAt: string, config: { __typename: 'PageConfigRecord', handle: string | null, seo: { __typename: 'SeoField', noIndex: boolean | null } | null } }> };
