/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type SitemapPostsQueryVariables = Types.Exact<{
  first: Types.Scalars['IntType']['input'];
  skip: Types.Scalars['IntType']['input'];
}>;


export type SitemapPostsQuery = { __typename: 'Query', allPosts: Array<{ __typename: 'PostRecord', _updatedAt: string, config: { __typename: 'PostConfigRecord', handle: string | null, seo: { __typename: 'SeoField', noIndex: boolean | null } | null } }> };
