/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */

export type JSONValue =
  | string
  | number
  | boolean
  | { [x: string]: JSONValue }
  | Array<JSONValue>

import type * as Types from '../base-types'

export type SupercarContentSectionsFragment = {
  __typename: 'SupercarContentRecord'
  sections: Array<
    | {
        __typename: 'SectionAccordionRecord'
        id: string
        title: string | null
        subtitle: string | null
        layout: string | null
        config: {
          __typename: 'SectionConfigRecord'
          id: string
          customId: string | null
          enabled: boolean
        } | null
        accordion: Array<{
          __typename: 'CoreAccordionRecord'
          id: string
          title: string
          body: string | null
          media: Array<
            | {
                __typename: 'CoreImageRecord'
                id: string
                image: {
                  __typename: 'FileField'
                  id: string
                  format: string
                  url: string
                  width: number | null
                  height: number | null
                  alt: string | null
                  title: string | null
                  focalPoint: {
                    __typename: 'focalPoint'
                    x: number
                    y: number
                  } | null
                  responsiveImage: {
                    __typename: 'ResponsiveImage'
                    src: string
                    srcSet: string
                    sizes: string
                    height: number
                    aspectRatio: number
                    width: number
                    alt: string | null
                    title: string | null
                    base64: string | null
                    bgColor: string | null
                  } | null
                } | null
                desktopImage: {
                  __typename: 'FileField'
                  id: string
                  format: string
                  url: string
                  width: number | null
                  height: number | null
                  alt: string | null
                  title: string | null
                  focalPoint: {
                    __typename: 'focalPoint'
                    x: number
                    y: number
                  } | null
                  responsiveImage: {
                    __typename: 'ResponsiveImage'
                    src: string
                    srcSet: string
                    sizes: string
                    height: number
                    aspectRatio: number
                    width: number
                    alt: string | null
                    title: string | null
                    base64: string | null
                    bgColor: string | null
                  } | null
                } | null
              }
            | {
                __typename: 'CoreVideoRecord'
                id: string
                controls: boolean
                autoplay: boolean
                loop: boolean
                customPosterImage: {
                  __typename: 'AltFileField'
                  url: string
                  alt: string
                  responsiveImage: {
                    __typename: 'ResponsiveImage'
                    width: number
                    webpSrcSet: string
                    title: string | null
                    srcSet: string
                    src: string
                    sizes: string
                    height: number
                    bgColor: string | null
                    base64: string | null
                    aspectRatio: number
                    alt: string | null
                  } | null
                } | null
                video: {
                  __typename: 'VideoFileField'
                  id: string
                  video: {
                    __typename: 'UploadVideoField'
                    width: number
                    height: number
                    streamingUrl: string
                    thumbnailUrl: string
                  }
                } | null
                desktopVideo: {
                  __typename: 'VideoFileField'
                  id: string
                  video: {
                    __typename: 'UploadVideoField'
                    width: number
                    height: number
                    streamingUrl: string
                    thumbnailUrl: string
                  }
                } | null
              }
          >
        }>
        ctas: Array<{
          __typename: 'CoreCtaRecord'
          id: string
          title: string | null
          path: string | null
          style: string | null
          size: string | null
          target: string | null
          action: string | null
          link:
            | {
                __typename: 'PageRecord'
                entry: { __typename: 'PageConfigRecord'; handle: string | null }
              }
            | {
                __typename: 'PostRecord'
                entry: { __typename: 'PostConfigRecord'; handle: string | null }
              }
            | {
                __typename: 'SupercarRecord'
                entry: {
                  __typename: 'SupercarConfigRecord'
                  handle: string | null
                }
              }
            | {
                __typename: 'TrackRecord'
                entry: {
                  __typename: 'TrackConfigRecord'
                  handle: string | null
                }
              }
            | null
        }>
      }
    | {
        __typename: 'SectionEventsFeatureRecord'
        id: string
        title: string | null
        subtitle: string | null
        description: string | null
        config: {
          __typename: 'SectionConfigRecord'
          id: string
          customId: string | null
          enabled: boolean
        } | null
        events: Array<{
          __typename: 'EventRecord'
          id: string
          titleInternal: string
          model: {
            __typename: 'EventModelRecord'
            id: string
            title: string | null
            date: string | null
            endDate: string | null
            rocketRezId: string | null
            track: {
              __typename: 'TrackRecord'
              id: string
              titleInternal: string
              config: {
                __typename: 'TrackConfigRecord'
                id: string
                title: string | null
                handle: string | null
                seo: {
                  __typename: 'SeoField'
                  title: string | null
                  description: string | null
                  noIndex: boolean | null
                  twitterCard: string | null
                  image: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                } | null
              }
              model: {
                __typename: 'TrackModelRecord'
                id: string
                title: string | null
                description: string | null
                nickname: string | null
                city: string | null
                state: string | null
                region: string | null
                address: string | null
                highlights: string | null
                lapLength: string | null
                numberOfLaps: string | null
                numberOfTurns: string | null
                longestStraight: string | null
                elevationChange: string | null
                travelTimes: string | null
                rocketRezId: string | null
                location: {
                  __typename: 'LatLonField'
                  latitude: number
                  longitude: number
                } | null
                thumbnail: {
                  __typename: 'CoreImageRecord'
                  id: string
                  image: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                  desktopImage: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                } | null
                featuredMedia:
                  | {
                      __typename: 'CoreImageRecord'
                      id: string
                      image: {
                        __typename: 'FileField'
                        id: string
                        format: string
                        url: string
                        width: number | null
                        height: number | null
                        alt: string | null
                        title: string | null
                        focalPoint: {
                          __typename: 'focalPoint'
                          x: number
                          y: number
                        } | null
                        responsiveImage: {
                          __typename: 'ResponsiveImage'
                          src: string
                          srcSet: string
                          sizes: string
                          height: number
                          aspectRatio: number
                          width: number
                          alt: string | null
                          title: string | null
                          base64: string | null
                          bgColor: string | null
                        } | null
                      } | null
                      desktopImage: {
                        __typename: 'FileField'
                        id: string
                        format: string
                        url: string
                        width: number | null
                        height: number | null
                        alt: string | null
                        title: string | null
                        focalPoint: {
                          __typename: 'focalPoint'
                          x: number
                          y: number
                        } | null
                        responsiveImage: {
                          __typename: 'ResponsiveImage'
                          src: string
                          srcSet: string
                          sizes: string
                          height: number
                          aspectRatio: number
                          width: number
                          alt: string | null
                          title: string | null
                          base64: string | null
                          bgColor: string | null
                        } | null
                      } | null
                    }
                  | {
                      __typename: 'CoreVideoRecord'
                      id: string
                      controls: boolean
                      autoplay: boolean
                      loop: boolean
                      customPosterImage: {
                        __typename: 'AltFileField'
                        url: string
                        alt: string
                        responsiveImage: {
                          __typename: 'ResponsiveImage'
                          width: number
                          webpSrcSet: string
                          title: string | null
                          srcSet: string
                          src: string
                          sizes: string
                          height: number
                          bgColor: string | null
                          base64: string | null
                          aspectRatio: number
                          alt: string | null
                        } | null
                      } | null
                      video: {
                        __typename: 'VideoFileField'
                        id: string
                        video: {
                          __typename: 'UploadVideoField'
                          width: number
                          height: number
                          streamingUrl: string
                          thumbnailUrl: string
                        }
                      } | null
                      desktopVideo: {
                        __typename: 'VideoFileField'
                        id: string
                        video: {
                          __typename: 'UploadVideoField'
                          width: number
                          height: number
                          streamingUrl: string
                          thumbnailUrl: string
                        }
                      } | null
                    }
                  | null
                gallery: Array<
                  | {
                      __typename: 'CoreImageRecord'
                      id: string
                      image: {
                        __typename: 'FileField'
                        id: string
                        format: string
                        url: string
                        width: number | null
                        height: number | null
                        alt: string | null
                        title: string | null
                        focalPoint: {
                          __typename: 'focalPoint'
                          x: number
                          y: number
                        } | null
                        responsiveImage: {
                          __typename: 'ResponsiveImage'
                          src: string
                          srcSet: string
                          sizes: string
                          height: number
                          aspectRatio: number
                          width: number
                          alt: string | null
                          title: string | null
                          base64: string | null
                          bgColor: string | null
                        } | null
                      } | null
                      desktopImage: {
                        __typename: 'FileField'
                        id: string
                        format: string
                        url: string
                        width: number | null
                        height: number | null
                        alt: string | null
                        title: string | null
                        focalPoint: {
                          __typename: 'focalPoint'
                          x: number
                          y: number
                        } | null
                        responsiveImage: {
                          __typename: 'ResponsiveImage'
                          src: string
                          srcSet: string
                          sizes: string
                          height: number
                          aspectRatio: number
                          width: number
                          alt: string | null
                          title: string | null
                          base64: string | null
                          bgColor: string | null
                        } | null
                      } | null
                    }
                  | {
                      __typename: 'CoreVideoRecord'
                      id: string
                      controls: boolean
                      autoplay: boolean
                      loop: boolean
                      customPosterImage: {
                        __typename: 'AltFileField'
                        url: string
                        alt: string
                        responsiveImage: {
                          __typename: 'ResponsiveImage'
                          width: number
                          webpSrcSet: string
                          title: string | null
                          srcSet: string
                          src: string
                          sizes: string
                          height: number
                          bgColor: string | null
                          base64: string | null
                          aspectRatio: number
                          alt: string | null
                        } | null
                      } | null
                      video: {
                        __typename: 'VideoFileField'
                        id: string
                        video: {
                          __typename: 'UploadVideoField'
                          width: number
                          height: number
                          streamingUrl: string
                          thumbnailUrl: string
                        }
                      } | null
                      desktopVideo: {
                        __typename: 'VideoFileField'
                        id: string
                        video: {
                          __typename: 'UploadVideoField'
                          width: number
                          height: number
                          streamingUrl: string
                          thumbnailUrl: string
                        }
                      } | null
                    }
                >
                badges: Array<{
                  __typename: 'CoreBadgeRecord'
                  id: string
                  label: string | null
                  backgroundColor: {
                    __typename: 'ColorField'
                    hex: string
                  } | null
                  color: { __typename: 'ColorField'; hex: string } | null
                }>
              } | null
            } | null
            media:
              | {
                  __typename: 'CoreImageRecord'
                  id: string
                  image: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                  desktopImage: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                }
              | {
                  __typename: 'CoreVideoRecord'
                  id: string
                  controls: boolean
                  autoplay: boolean
                  loop: boolean
                  customPosterImage: {
                    __typename: 'AltFileField'
                    url: string
                    alt: string
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      width: number
                      webpSrcSet: string
                      title: string | null
                      srcSet: string
                      src: string
                      sizes: string
                      height: number
                      bgColor: string | null
                      base64: string | null
                      aspectRatio: number
                      alt: string | null
                    } | null
                  } | null
                  video: {
                    __typename: 'VideoFileField'
                    id: string
                    video: {
                      __typename: 'UploadVideoField'
                      width: number
                      height: number
                      streamingUrl: string
                      thumbnailUrl: string
                    }
                  } | null
                  desktopVideo: {
                    __typename: 'VideoFileField'
                    id: string
                    video: {
                      __typename: 'UploadVideoField'
                      width: number
                      height: number
                      streamingUrl: string
                      thumbnailUrl: string
                    }
                  } | null
                }
              | null
          } | null
        }>
        ctas: Array<{
          __typename: 'CoreCtaRecord'
          id: string
          title: string | null
          path: string | null
          style: string | null
          size: string | null
          target: string | null
          action: string | null
          link:
            | {
                __typename: 'PageRecord'
                entry: { __typename: 'PageConfigRecord'; handle: string | null }
              }
            | {
                __typename: 'PostRecord'
                entry: { __typename: 'PostConfigRecord'; handle: string | null }
              }
            | {
                __typename: 'SupercarRecord'
                entry: {
                  __typename: 'SupercarConfigRecord'
                  handle: string | null
                }
              }
            | {
                __typename: 'TrackRecord'
                entry: {
                  __typename: 'TrackConfigRecord'
                  handle: string | null
                }
              }
            | null
        }>
      }
    | {
        __typename: 'SectionFaqRecord'
        id: string
        title: string | null
        subtitle: string | null
        description: string | null
        config: {
          __typename: 'SectionConfigRecord'
          id: string
          customId: string | null
          enabled: boolean
        } | null
        faqs: Array<{
          __typename: 'FaqRecord'
          id: string
          titleInternal: string | null
          config: {
            __typename: 'FaqConfigRecord'
            id: string
            title: string | null
            handle: string | null
            seo: {
              __typename: 'SeoField'
              title: string | null
              description: string | null
              noIndex: boolean | null
              twitterCard: string | null
              image: {
                __typename: 'FileField'
                id: string
                format: string
                url: string
                width: number | null
                height: number | null
                alt: string | null
                title: string | null
                focalPoint: {
                  __typename: 'focalPoint'
                  x: number
                  y: number
                } | null
                responsiveImage: {
                  __typename: 'ResponsiveImage'
                  src: string
                  srcSet: string
                  sizes: string
                  height: number
                  aspectRatio: number
                  width: number
                  alt: string | null
                  title: string | null
                  base64: string | null
                  bgColor: string | null
                } | null
              } | null
            } | null
          } | null
          model: {
            __typename: 'FaqModelRecord'
            id: string
            title: string | null
            faqs: Array<{
              __typename: 'CoreAccordionRecord'
              id: string
              title: string
              body: string | null
              media: Array<
                | {
                    __typename: 'CoreImageRecord'
                    id: string
                    image: {
                      __typename: 'FileField'
                      id: string
                      format: string
                      url: string
                      width: number | null
                      height: number | null
                      alt: string | null
                      title: string | null
                      focalPoint: {
                        __typename: 'focalPoint'
                        x: number
                        y: number
                      } | null
                      responsiveImage: {
                        __typename: 'ResponsiveImage'
                        src: string
                        srcSet: string
                        sizes: string
                        height: number
                        aspectRatio: number
                        width: number
                        alt: string | null
                        title: string | null
                        base64: string | null
                        bgColor: string | null
                      } | null
                    } | null
                    desktopImage: {
                      __typename: 'FileField'
                      id: string
                      format: string
                      url: string
                      width: number | null
                      height: number | null
                      alt: string | null
                      title: string | null
                      focalPoint: {
                        __typename: 'focalPoint'
                        x: number
                        y: number
                      } | null
                      responsiveImage: {
                        __typename: 'ResponsiveImage'
                        src: string
                        srcSet: string
                        sizes: string
                        height: number
                        aspectRatio: number
                        width: number
                        alt: string | null
                        title: string | null
                        base64: string | null
                        bgColor: string | null
                      } | null
                    } | null
                  }
                | {
                    __typename: 'CoreVideoRecord'
                    id: string
                    controls: boolean
                    autoplay: boolean
                    loop: boolean
                    customPosterImage: {
                      __typename: 'AltFileField'
                      url: string
                      alt: string
                      responsiveImage: {
                        __typename: 'ResponsiveImage'
                        width: number
                        webpSrcSet: string
                        title: string | null
                        srcSet: string
                        src: string
                        sizes: string
                        height: number
                        bgColor: string | null
                        base64: string | null
                        aspectRatio: number
                        alt: string | null
                      } | null
                    } | null
                    video: {
                      __typename: 'VideoFileField'
                      id: string
                      video: {
                        __typename: 'UploadVideoField'
                        width: number
                        height: number
                        streamingUrl: string
                        thumbnailUrl: string
                      }
                    } | null
                    desktopVideo: {
                      __typename: 'VideoFileField'
                      id: string
                      video: {
                        __typename: 'UploadVideoField'
                        width: number
                        height: number
                        streamingUrl: string
                        thumbnailUrl: string
                      }
                    } | null
                  }
              >
            }>
          } | null
        }>
      }
    | {
        __typename: 'SectionMediaGalleryRecord'
        id: string
        title: string | null
        media:
          | {
              __typename: 'CoreImageRecord'
              id: string
              image: {
                __typename: 'FileField'
                id: string
                format: string
                url: string
                width: number | null
                height: number | null
                alt: string | null
                title: string | null
                focalPoint: {
                  __typename: 'focalPoint'
                  x: number
                  y: number
                } | null
                responsiveImage: {
                  __typename: 'ResponsiveImage'
                  src: string
                  srcSet: string
                  sizes: string
                  height: number
                  aspectRatio: number
                  width: number
                  alt: string | null
                  title: string | null
                  base64: string | null
                  bgColor: string | null
                } | null
              } | null
              desktopImage: {
                __typename: 'FileField'
                id: string
                format: string
                url: string
                width: number | null
                height: number | null
                alt: string | null
                title: string | null
                focalPoint: {
                  __typename: 'focalPoint'
                  x: number
                  y: number
                } | null
                responsiveImage: {
                  __typename: 'ResponsiveImage'
                  src: string
                  srcSet: string
                  sizes: string
                  height: number
                  aspectRatio: number
                  width: number
                  alt: string | null
                  title: string | null
                  base64: string | null
                  bgColor: string | null
                } | null
              } | null
            }
          | {
              __typename: 'CoreVideoRecord'
              id: string
              controls: boolean
              autoplay: boolean
              loop: boolean
              customPosterImage: {
                __typename: 'AltFileField'
                url: string
                alt: string
                responsiveImage: {
                  __typename: 'ResponsiveImage'
                  width: number
                  webpSrcSet: string
                  title: string | null
                  srcSet: string
                  src: string
                  sizes: string
                  height: number
                  bgColor: string | null
                  base64: string | null
                  aspectRatio: number
                  alt: string | null
                } | null
              } | null
              video: {
                __typename: 'VideoFileField'
                id: string
                video: {
                  __typename: 'UploadVideoField'
                  width: number
                  height: number
                  streamingUrl: string
                  thumbnailUrl: string
                }
              } | null
              desktopVideo: {
                __typename: 'VideoFileField'
                id: string
                video: {
                  __typename: 'UploadVideoField'
                  width: number
                  height: number
                  streamingUrl: string
                  thumbnailUrl: string
                }
              } | null
            }
          | null
      }
    | {
        __typename: 'SectionReviewRecord'
        id: string
        title: string | null
        config: {
          __typename: 'SectionConfigRecord'
          id: string
          customId: string | null
          enabled: boolean
        } | null
        reviews: Array<{
          __typename: 'ReviewRecord'
          id: string
          titleInternal: string
          model: {
            __typename: 'ReviewModelRecord'
            id: string
            title: string | null
            attribution: string | null
            quote: string | null
            rating: number | null
            media:
              | {
                  __typename: 'CoreImageRecord'
                  id: string
                  image: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                  desktopImage: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                }
              | {
                  __typename: 'CoreVideoRecord'
                  id: string
                  controls: boolean
                  autoplay: boolean
                  loop: boolean
                  customPosterImage: {
                    __typename: 'AltFileField'
                    url: string
                    alt: string
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      width: number
                      webpSrcSet: string
                      title: string | null
                      srcSet: string
                      src: string
                      sizes: string
                      height: number
                      bgColor: string | null
                      base64: string | null
                      aspectRatio: number
                      alt: string | null
                    } | null
                  } | null
                  video: {
                    __typename: 'VideoFileField'
                    id: string
                    video: {
                      __typename: 'UploadVideoField'
                      width: number
                      height: number
                      streamingUrl: string
                      thumbnailUrl: string
                    }
                  } | null
                  desktopVideo: {
                    __typename: 'VideoFileField'
                    id: string
                    video: {
                      __typename: 'UploadVideoField'
                      width: number
                      height: number
                      streamingUrl: string
                      thumbnailUrl: string
                    }
                  } | null
                }
              | null
          } | null
        }>
        ctas: Array<{
          __typename: 'CoreCtaRecord'
          id: string
          title: string | null
          path: string | null
          style: string | null
          size: string | null
          target: string | null
          action: string | null
          link:
            | {
                __typename: 'PageRecord'
                entry: { __typename: 'PageConfigRecord'; handle: string | null }
              }
            | {
                __typename: 'PostRecord'
                entry: { __typename: 'PostConfigRecord'; handle: string | null }
              }
            | {
                __typename: 'SupercarRecord'
                entry: {
                  __typename: 'SupercarConfigRecord'
                  handle: string | null
                }
              }
            | {
                __typename: 'TrackRecord'
                entry: {
                  __typename: 'TrackConfigRecord'
                  handle: string | null
                }
              }
            | null
        }>
      }
    | {
        __typename: 'SectionSupercarBrandHeroRecord'
        id: string
        config: {
          __typename: 'SectionConfigRecord'
          id: string
          customId: string | null
          enabled: boolean
        } | null
        logo: {
          __typename: 'FileField'
          id: string
          url: string
          alt: string | null
          title: string | null
        } | null
        audio: { __typename: 'FileField'; id: string; url: string } | null
        gradient: {
          __typename: 'CoreGradientRecord'
          enabled: boolean
          direction: string | null
          customCssGradient: string | null
          startColor: { __typename: 'ColorField'; cssRgb: string } | null
          endColor: { __typename: 'ColorField'; cssRgb: string } | null
        } | null
        media:
          | {
              __typename: 'CoreImageRecord'
              id: string
              image: {
                __typename: 'FileField'
                id: string
                format: string
                url: string
                width: number | null
                height: number | null
                alt: string | null
                title: string | null
                focalPoint: {
                  __typename: 'focalPoint'
                  x: number
                  y: number
                } | null
                responsiveImage: {
                  __typename: 'ResponsiveImage'
                  src: string
                  srcSet: string
                  sizes: string
                  height: number
                  aspectRatio: number
                  width: number
                  alt: string | null
                  title: string | null
                  base64: string | null
                  bgColor: string | null
                } | null
              } | null
              desktopImage: {
                __typename: 'FileField'
                id: string
                format: string
                url: string
                width: number | null
                height: number | null
                alt: string | null
                title: string | null
                focalPoint: {
                  __typename: 'focalPoint'
                  x: number
                  y: number
                } | null
                responsiveImage: {
                  __typename: 'ResponsiveImage'
                  src: string
                  srcSet: string
                  sizes: string
                  height: number
                  aspectRatio: number
                  width: number
                  alt: string | null
                  title: string | null
                  base64: string | null
                  bgColor: string | null
                } | null
              } | null
            }
          | {
              __typename: 'CoreVideoRecord'
              id: string
              controls: boolean
              autoplay: boolean
              loop: boolean
              customPosterImage: {
                __typename: 'AltFileField'
                url: string
                alt: string
                responsiveImage: {
                  __typename: 'ResponsiveImage'
                  width: number
                  webpSrcSet: string
                  title: string | null
                  srcSet: string
                  src: string
                  sizes: string
                  height: number
                  bgColor: string | null
                  base64: string | null
                  aspectRatio: number
                  alt: string | null
                } | null
              } | null
              video: {
                __typename: 'VideoFileField'
                id: string
                video: {
                  __typename: 'UploadVideoField'
                  width: number
                  height: number
                  streamingUrl: string
                  thumbnailUrl: string
                }
              } | null
              desktopVideo: {
                __typename: 'VideoFileField'
                id: string
                video: {
                  __typename: 'UploadVideoField'
                  width: number
                  height: number
                  streamingUrl: string
                  thumbnailUrl: string
                }
              } | null
            }
          | null
      }
    | {
        __typename: 'SectionSupercarFleetGridRecord'
        id: string
        title: string | null
        config: {
          __typename: 'SectionConfigRecord'
          id: string
          customId: string | null
          enabled: boolean
        } | null
        supercars: Array<{
          __typename: 'SupercarRecord'
          id: string
          titleInternal: string
          config: {
            __typename: 'SupercarConfigRecord'
            id: string
            title: string | null
            handle: string | null
            seo: {
              __typename: 'SeoField'
              title: string | null
              description: string | null
              noIndex: boolean | null
              twitterCard: string | null
              image: {
                __typename: 'FileField'
                id: string
                format: string
                url: string
                width: number | null
                height: number | null
                alt: string | null
                title: string | null
                focalPoint: {
                  __typename: 'focalPoint'
                  x: number
                  y: number
                } | null
                responsiveImage: {
                  __typename: 'ResponsiveImage'
                  src: string
                  srcSet: string
                  sizes: string
                  height: number
                  aspectRatio: number
                  width: number
                  alt: string | null
                  title: string | null
                  base64: string | null
                  bgColor: string | null
                } | null
              } | null
            } | null
          }
          model: {
            __typename: 'SupercarModelRecord'
            id: string
            title: string | null
            description: string | null
            make: string | null
            model: string | null
            origin: string | null
            packageType: string
            rocketRezId: string | null
            engine: string | null
            horsepower: string | null
            torque: string | null
            transmission: string | null
            topSpeed: string | null
            zeroToSixty: string | null
            weight: string | null
            vehicleLayout: string | null
            value: string | null
            maxParticipantHeight: string | null
            startingPriceFor3Laps: string | null
            thumbnail: {
              __typename: 'CoreImageRecord'
              id: string
              image: {
                __typename: 'FileField'
                id: string
                format: string
                url: string
                width: number | null
                height: number | null
                alt: string | null
                title: string | null
                focalPoint: {
                  __typename: 'focalPoint'
                  x: number
                  y: number
                } | null
                responsiveImage: {
                  __typename: 'ResponsiveImage'
                  src: string
                  srcSet: string
                  sizes: string
                  height: number
                  aspectRatio: number
                  width: number
                  alt: string | null
                  title: string | null
                  base64: string | null
                  bgColor: string | null
                } | null
              } | null
              desktopImage: {
                __typename: 'FileField'
                id: string
                format: string
                url: string
                width: number | null
                height: number | null
                alt: string | null
                title: string | null
                focalPoint: {
                  __typename: 'focalPoint'
                  x: number
                  y: number
                } | null
                responsiveImage: {
                  __typename: 'ResponsiveImage'
                  src: string
                  srcSet: string
                  sizes: string
                  height: number
                  aspectRatio: number
                  width: number
                  alt: string | null
                  title: string | null
                  base64: string | null
                  bgColor: string | null
                } | null
              } | null
            } | null
            featuredMedia:
              | {
                  __typename: 'CoreImageRecord'
                  id: string
                  image: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                  desktopImage: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                }
              | {
                  __typename: 'CoreVideoRecord'
                  id: string
                  controls: boolean
                  autoplay: boolean
                  loop: boolean
                  customPosterImage: {
                    __typename: 'AltFileField'
                    url: string
                    alt: string
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      width: number
                      webpSrcSet: string
                      title: string | null
                      srcSet: string
                      src: string
                      sizes: string
                      height: number
                      bgColor: string | null
                      base64: string | null
                      aspectRatio: number
                      alt: string | null
                    } | null
                  } | null
                  video: {
                    __typename: 'VideoFileField'
                    id: string
                    video: {
                      __typename: 'UploadVideoField'
                      width: number
                      height: number
                      streamingUrl: string
                      thumbnailUrl: string
                    }
                  } | null
                  desktopVideo: {
                    __typename: 'VideoFileField'
                    id: string
                    video: {
                      __typename: 'UploadVideoField'
                      width: number
                      height: number
                      streamingUrl: string
                      thumbnailUrl: string
                    }
                  } | null
                }
              | null
            gallery: Array<
              | {
                  __typename: 'CoreImageRecord'
                  id: string
                  image: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                  desktopImage: {
                    __typename: 'FileField'
                    id: string
                    format: string
                    url: string
                    width: number | null
                    height: number | null
                    alt: string | null
                    title: string | null
                    focalPoint: {
                      __typename: 'focalPoint'
                      x: number
                      y: number
                    } | null
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      src: string
                      srcSet: string
                      sizes: string
                      height: number
                      aspectRatio: number
                      width: number
                      alt: string | null
                      title: string | null
                      base64: string | null
                      bgColor: string | null
                    } | null
                  } | null
                }
              | {
                  __typename: 'CoreVideoRecord'
                  id: string
                  controls: boolean
                  autoplay: boolean
                  loop: boolean
                  customPosterImage: {
                    __typename: 'AltFileField'
                    url: string
                    alt: string
                    responsiveImage: {
                      __typename: 'ResponsiveImage'
                      width: number
                      webpSrcSet: string
                      title: string | null
                      srcSet: string
                      src: string
                      sizes: string
                      height: number
                      bgColor: string | null
                      base64: string | null
                      aspectRatio: number
                      alt: string | null
                    } | null
                  } | null
                  video: {
                    __typename: 'VideoFileField'
                    id: string
                    video: {
                      __typename: 'UploadVideoField'
                      width: number
                      height: number
                      streamingUrl: string
                      thumbnailUrl: string
                    }
                  } | null
                  desktopVideo: {
                    __typename: 'VideoFileField'
                    id: string
                    video: {
                      __typename: 'UploadVideoField'
                      width: number
                      height: number
                      streamingUrl: string
                      thumbnailUrl: string
                    }
                  } | null
                }
            >
            badges: Array<{
              __typename: 'CoreBadgeRecord'
              id: string
              label: string | null
              backgroundColor: { __typename: 'ColorField'; hex: string } | null
              color: { __typename: 'ColorField'; hex: string } | null
            }>
            displayPrice: {
              __typename: 'CorePriceRecord'
              id: string
              compareAtPrice: number | null
              price: number | null
            } | null
          } | null
        }>
      }
    | {
        __typename: 'SectionSupercarHeroRecord'
        id: string
        titleInternal: string | null
      }
    | {
        __typename: 'SectionSupercarSpecRecord'
        id: string
        titleInternal: string | null
      }
  >
}
