/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../base-types';

export type VideoFragment = { __typename: 'VideoFileField', id: string, video: { __typename: 'UploadVideoField', width: number, height: number, streamingUrl: string, thumbnailUrl: string, mp4Low: string | null, mp4Medium: string | null, mp4High: string | null } };
