/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type SectionUspFragment = { __typename: 'SectionUspRecord', id: string, config: { __typename: 'SectionConfigRecord', id: string, customId: string | null, enabled: boolean, mode: string | null, highlightColor: string | null, contrastColor: string | null, addBottomBorder: boolean, addFlagPattern: boolean } | null, cards: Array<{ __typename: 'CoreUspRecord', id: string, horizontalAlignment: string | null, title: string | null, subtitle: string | null, description: string | null, icon: { __typename: 'CoreIconRecord', id: string, icon: string | null } | null }> };
