/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type CoreUspFragment = { __typename: 'CoreUspRecord', id: string, horizontalAlignment: string | null, title: string | null, subtitle: string | null, description: string | null, icon: { __typename: 'CoreIconRecord', id: string, icon: string | null } | null };
