/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type SectionPolicyFragment = { __typename: 'SectionPolicyRecord', id: string, title: string | null, subtitle: string | null, config: { __typename: 'SectionConfigRecord', id: string, customId: string | null, enabled: boolean, mode: string | null, highlightColor: string | null, contrastColor: string | null, addBottomBorder: boolean, addFlagPattern: boolean } | null, policies: Array<{ __typename: 'PolicyRecord', id: string, model: { __typename: 'PolicyModelRecord', id: string, title: string | null, body: string | null } | null }> };
