/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type CoreVideoFragment = { __typename: 'CoreVideoRecord', id: string, controls: boolean, autoplay: boolean, loop: boolean, videoRawMp4FileUrl: string | null, desktopVideoRawMp4FileUrl: string | null, customPosterImage: { __typename: 'AltFileField', url: string, alt: string, responsiveImage: { __typename: 'ResponsiveImage', width: number, webpSrcSet: string, title: string | null, srcSet: string, src: string, sizes: string, height: number, bgColor: string | null, base64: string | null, aspectRatio: number, alt: string | null } | null } | null, video: { __typename: 'VideoFileField', id: string, video: { __typename: 'UploadVideoField', width: number, height: number, streamingUrl: string, thumbnailUrl: string, mp4Low: string | null, mp4Medium: string | null, mp4High: string | null } } | null, desktopVideo: { __typename: 'VideoFileField', id: string, video: { __typename: 'UploadVideoField', width: number, height: number, streamingUrl: string, thumbnailUrl: string, mp4Low: string | null, mp4Medium: string | null, mp4High: string | null } } | null };
