/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type CoreBadgeFragment = { __typename: 'CoreBadgeRecord', id: string, label: string | null, backgroundColor: { __typename: 'ColorField', hex: string } | null, color: { __typename: 'ColorField', hex: string } | null };
