/* eslint-disable */
/* DO NOT EDIT! Generated by GraphQL Codegen. */


export type JSONValue = string | number | boolean | { [x: string]: JSONValue } | Array<JSONValue>;


import type * as Types from '../../core/dato/base-types';

export type GetAllCategoriesQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type GetAllCategoriesQuery = { __typename: 'Query', allCategories: Array<{ __typename: 'CategoryRecord', id: string, model: { __typename: 'CategoryModelRecord', handle: string | null, title: string | null } | null }> };
