name: 'Sync Typesense (Production)'

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'Sync mode'
        type: choice
        required: true
        default: new
        options:
          - new
          - all

jobs:
  sync-typesense-prod:
    runs-on: 'ubuntu-latest'
    environment:
      name: production
    concurrency:
      group: 'sync-typesense-prod'
      cancel-in-progress: true
    env:
      COMPOSE_BAKE: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      COMPOSE_PROJECT_NAME: 'sync-typesense-prod'
      DOCKER_BUILDKIT: 1
      TYPESENSE_BASE_URL: ${{ vars.TYPESENSE_BASE_URL }}
      TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
      NEXT_PUBLIC_DATOCMS_READONLY_TOKEN: ${{ secrets.NEXT_PUBLIC_DATOCMS_READONLY_TOKEN }}
      NEXT_PUBLIC_DATOCMS_ENVIRONMENT: ${{ vars.NEXT_PUBLIC_DATOCMS_ENVIRONMENT }}
      SYNC_MODE: ${{ github.event_name == 'workflow_dispatch' && inputs.mode || 'new' }}
    steps:
      - name: 'Checkout everything'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
          token: ${{ secrets.CHECKOUT_ACTION_PAT }}

      - name: 'Init git config'
        run: |
          git config --global user.name 'Autobot'
          git config --global user.email 'engineering@vaangroup.com'
        # Workaround for No TTY issue
        shell: 'script -qec "bash {0}"'

      - name: 'Bootstrap TMP_DIR'
        run: |
          ./devops/github/bootstrap-tmp-dir.sh
        shell: 'script -qec "bash {0}"'

      - name: 'Build and start `main_ci` container'
        run: |
          touch .env
          docker compose build \
              --build-arg GROUP_ID=$(id -g) --build-arg USER_ID=$(id -u) \
              --progress=plain main_ci \
            && docker compose up -d main_ci
        shell: 'script -qec "bash {0}"'

      - name: 'Install npm packages'
        run: |
          docker compose exec main_ci ./docker-entrypoint.sh
        shell: 'script -qec "bash {0}"'

      - name: 'Sync Typesense'
        run: |
          echo "Sync mode: ${SYNC_MODE}"
          docker compose exec main_ci /bin/bash -c "pnpm run sync-typesense:${SYNC_MODE}"
        shell: 'script -qec "bash {0}"'

      - name: 'Shutdown containers'
        run: |
          ./devops/ci/shutdown-ci-container.sh
        shell: 'script -qec "bash {0}"'
